apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::843739472387:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DK3294YKHCI6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::843739472387:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-28T14:48:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1387"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4c10023a-5316-4946-9f96-f27fb17664d3
